FROM alpine:3.18

RUN apk update && apk upgrade

# RUN
# install everything needed for nginx

# COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# COPY ./tools/nginx.sh /tmp/nginx.sh

# EXPOSE 443

# CMD ["bash -sh", "-g", ";"]
